### PR TITLE
add todo tasks functionalities

### PR DESCRIPTION
**Pull request by linnnruoo**
todo tt/Write tests c/write test for newly added features

### CODE REVIEW

**Comment by linnnruoo** [comment]
@jitwei98 any idea why travis is not tracking this??

**Comment by linnnruoo** [comment]
@jitwei98 I am very sad

**Comment by linnnruoo** [comment]
@jitwei98 yay can merge and close the pr?

**Comment by jitwei98** [comment]
Good job on the new feature!

**Pull request merged**
