### PR TITLE
change browsePanel content

### PR DESCRIPTION
**Pull request by linnnruoo**
image

this is the current look. If our theme shifts towards delivery services, the browsepanel content will make some sort of sense

### CODE REVIEW

**Comment by linnnruoo** [comment]
@jitwei98 wah it failed at the browsepanel, should i remove its associated tests?

**Comment by linnnruoo** [comment]
image

Revert back to this one as the one with google map fails some of the system tests
**Propose**: remove some of the system tests for browserPanel or completely remove it

**Comment by jitwei98** [comment]
Should I merge this?

**Comment by linnnruoo** [comment]
@jitwei98  it will be updated automatically once the binary file has been changed

**Comment by jitwei98** [comment]
@linnnruoo  ok noted!

**Pull request merged**
